//! Engine lubrication system.
//!
//! A single oil reservoir per engine.  The simulation tracks four numbers:
//!
//!   * `mass`        — kg of oil in the sump (drops if blow-by burns it)
//!   * `temperature` — K (warms from cylinder/friction heat, cools through the pan)
//!   * `pressure`    — Pa (generated by the crank-driven pump, capped at relief)
//!   * `viscosity`   — Pa·s (Arrhenius curve in temperature)
//!
//! These four feed [`OilState::lubrication_factor`], a `0..=1` knob that the
//! material contact-mechanics in [`super::material`] use to interpolate between
//! "dry boundary" wear and "fully hydrodynamic" zero-wear operation.

use std::f32::consts::TAU;

use super::thermo::T_ATM;

/// Tunable parameters of the lubrication system (per-engine).
#[derive(Clone, Debug)]
pub struct OilConfig {
    /// Capacity (kg) — full sump.
    pub capacity: f32,
    /// Volumetric pump displacement per revolution (m³/rev).
    pub pump_displacement: f32,
    /// Relief-valve set point (Pa).  Pressure caps here.
    pub relief_pressure: f32,
    /// If sump mass falls below this, the pickup uncovers and pressure dies.
    pub min_pickup_mass: f32,
    /// Combined oil-pan dissipation coefficient (W/K).  Newton cooling to ambient.
    pub pan_dissipation: f32,
    /// Pressure (Pa) above which the film is considered fully hydrodynamic.
    pub hydrodynamic_pressure: f32,
}

impl Default for OilConfig {
    fn default() -> Self {
        Self {
            capacity: 4.0,                   // ~4.5 L of 5W-30
            pump_displacement: 1.2e-5,       // m³/rev
            relief_pressure: 4.0e5,          // 400 kPa = ~58 PSI
            min_pickup_mass: 0.4,
            pan_dissipation: 18.0,
            hydrodynamic_pressure: 2.0e5,    // 200 kPa = full film
        }
    }
}

/// Live state of the oil reservoir.
#[derive(Clone, Debug)]
pub struct OilState {
    pub mass: f32,
    pub temperature: f32,
    pub pressure: f32,
    pub viscosity: f32,
}

impl OilState {
    /// Cold, full-fill, zero pressure.
    pub fn fresh(cfg: &OilConfig) -> Self {
        let temperature = T_ATM;
        Self {
            mass: cfg.capacity,
            temperature,
            pressure: 0.0,
            viscosity: viscosity_for(temperature),
        }
    }

    /// Sump full enough for the pickup to draw.
    #[inline]
    pub fn has_pickup(&self, cfg: &OilConfig) -> bool {
        self.mass > cfg.min_pickup_mass
    }

    /// 0..=1 lubrication regime.  0 = dry boundary, 1 = full hydrodynamic film.
    pub fn lubrication_factor(&self, cfg: &OilConfig) -> f32 {
        if !self.has_pickup(cfg) {
            return 0.0;
        }
        (self.pressure / cfg.hydrodynamic_pressure).clamp(0.0, 1.0)
    }

    /// Step the oil one substep.
    ///
    /// `omega`             — current crank speed (rad/s)
    /// `friction_heat_w`   — W of mechanical heat dumped into the oil this step
    /// `cylinder_heat_w`   — W of combustion-side heat the oil absorbs
    /// `dt`                — substep length (s)
    pub fn step(
        &mut self,
        cfg: &OilConfig,
        omega: f32,
        friction_heat_w: f32,
        cylinder_heat_w: f32,
        dt: f32,
    ) {
        // ── Viscosity from current temperature ─────────────────────────────
        self.viscosity = viscosity_for(self.temperature);

        // ── Pump pressure ──────────────────────────────────────────────────
        // Flow rate ∝ rpm.  Pressure ≈ flow * viscosity * lumped resistance.
        // The resistance constant is tuned so a warm idle sits near 200 kPa
        // and the relief opens at typical operating RPM.
        if self.has_pickup(cfg) {
            const PUMP_RESISTANCE: f32 = 1.6e8; // Pa·s/m³
            let revs_per_s = omega / TAU;
            let flow = (cfg.pump_displacement * revs_per_s).max(0.0);
            let raw_pressure = flow * self.viscosity * PUMP_RESISTANCE;
            // Smooth toward the new pressure to avoid step discontinuities at the
            // relief and at startup.
            let target = raw_pressure.min(cfg.relief_pressure);
            let alpha = (10.0 * dt).min(1.0);
            self.pressure += (target - self.pressure) * alpha;
        } else {
            // Pickup uncovered — pressure collapses immediately.
            self.pressure *= (1.0 - 20.0 * dt).max(0.0);
        }

        // ── Thermal balance ────────────────────────────────────────────────
        // Specific heat of oil ≈ 2000 J/(kg·K).
        const C_OIL: f32 = 2000.0;
        let mass_eff = self.mass.max(0.05);
        let q_in = friction_heat_w + cylinder_heat_w;
        let q_out = cfg.pan_dissipation * (self.temperature - T_ATM);
        let dT = (q_in - q_out) * dt / (mass_eff * C_OIL);
        self.temperature = (self.temperature + dT).clamp(T_ATM - 5.0, 600.0);
    }

    /// Manually empty the sump (for testing seizure).
    pub fn drain(&mut self) {
        self.mass = 0.0;
        self.pressure = 0.0;
    }

    /// Refill the sump to full and reset temperature.
    pub fn refill(&mut self, cfg: &OilConfig) {
        self.mass = cfg.capacity;
        self.temperature = T_ATM;
        self.pressure = 0.0;
        self.viscosity = viscosity_for(self.temperature);
    }

    /// Burn off some oil mass (e.g. blow-by past worn rings).
    pub fn consume(&mut self, kg: f32) {
        self.mass = (self.mass - kg.max(0.0)).max(0.0);
    }
}

/// Andrade-style viscosity curve fitted to roughly 5W-30 behaviour:
/// 0.150 Pa·s at 293 K, 0.010 Pa·s at 373 K.
#[inline]
pub fn viscosity_for(temperature_k: f32) -> f32 {
    let t = temperature_k.max(220.0);
    (-14.53_f32 + 3700.0 / t).exp().clamp(0.001, 5.0)
}
