//! Engine lubrication system.
//!
//! A single oil reservoir per engine.  The simulation tracks four numbers:
//!
//!   * `mass`        — kg of oil in the sump (drops if blow-by burns it)
//!   * `temperature` — K (warms from cylinder/friction heat, cools through the pan)
//!   * `pressure`    — Pa (generated by the crank-driven pump, capped at relief)
//!   * `viscosity`   — Pa·s (Arrhenius curve in temperature)
//!
//! These four feed [`OilState::lubrication_factor`], a `0..=1` knob that the
//! material contact-mechanics in [`super::material`] use to interpolate between
//! "dry boundary" wear and "fully hydrodynamic" zero-wear operation.

use std::f32::consts::TAU;

use super::thermo::T_ATM;

/// SAE Oil Grade preset parameters.
#[derive(Clone, Copy, Debug)]
pub struct OilGrade {
    pub name: &'static str,
    /// Kinematic viscosity at 40°C (cSt).
    pub v40: f32,
    /// Kinematic viscosity at 100°C (cSt).
    pub v100: f32,
    pub description: &'static str,
}

pub const OIL_GRADES: &[OilGrade] = &[
    OilGrade {
        name: "0W-20",
        v40: 45.0, v100: 8.5,
        description: "Modern economy oil. Very thin, low friction.",
    },
    OilGrade {
        name: "5W-30",
        v40: 65.0, v100: 11.5,
        description: "Modern standard synthetic. Good balance.",
    },
    OilGrade {
        name: "10W-40",
        v40: 95.0, v100: 14.5,
        description: "Performance/European spec. Thicker film.",
    },
    OilGrade {
        name: "0W-40",
        v40: 75.0, v100: 13.5,
        description: "High-VI premium synthetic. Wide temperature range.",
    },
    OilGrade {
        name: "20W-50",
        v40: 160.0, v100: 19.5,
        description: "Classic/Racing oil. Very thick when cold.",
    },
];

/// Tunable parameters of the lubrication system (per-engine).
#[derive(Clone, Debug)]
pub struct OilConfig {
    /// Capacity (kg) — full sump.
    pub capacity: f32,
    /// Volumetric pump displacement per revolution (m³/rev).
    pub pump_displacement: f32,
    /// Relief-valve set point (Pa).  Pressure caps here.
    pub relief_pressure: f32,
    /// If sump mass falls below this, the pickup uncovers and pressure dies.
    pub min_pickup_mass: f32,
    /// Combined oil-pan dissipation coefficient (W/K).  Newton cooling to ambient.
    pub pan_dissipation: f32,
    /// External oil cooler dissipation coefficient (W/K).
    pub cooler_dissipation: f32,
    /// Is the electric cooling fan running?
    pub fan_active: bool,
    /// Pressure (Pa) above which the film is considered fully hydrodynamic.
    pub hydrodynamic_pressure: f32,
    /// Current oil grade index into `OIL_GRADES`.
    pub grade_idx: usize,
    /// Is a custom grade active?
    pub custom_grade: bool,
    /// Kinematic viscosity @ 40°C (cSt).
    pub v40: f32,
    /// Kinematic viscosity @ 100°C (cSt).
    pub v100: f32,
    /// Active Arrhenius offset (computed).
    pub viscosity_a: f32,
    /// Active Arrhenius slope (computed).
    pub viscosity_b: f32,
    /// User tuning multiplier on top of the base grade curve.
    pub viscosity_multiplier: f32,
}

impl Default for OilConfig {
    fn default() -> Self {
        let grade = OIL_GRADES[1]; // 5W-30
        let mut cfg = Self {
            capacity: 4.0,
            pump_displacement: 1.2e-5,
            relief_pressure: 4.0e5,
            min_pickup_mass: 0.4,
            pan_dissipation: 18.0,
            cooler_dissipation: 150.0,
            fan_active: false,
            hydrodynamic_pressure: 2.0e5,
            grade_idx: 1,
            custom_grade: false,
            v40: grade.v40,
            v100: grade.v100,
            viscosity_a: 0.0,
            viscosity_b: 0.0,
            viscosity_multiplier: 1.0,
        };
        cfg.recalculate_constants();
        cfg
    }
}

impl OilConfig {
    /// Solves for Arrhenius A and B based on v40 and v100 specs.
    pub fn recalculate_constants(&mut self) {
        let t1 = 313.15; // 40 C
        let t2 = 373.15; // 100 C
        
        // Dynamic viscosity mu (Pa.s) approx = cSt * 0.00085 (density)
        let mu1 = (self.v40 * 0.00085).max(1e-6);
        let mu2 = (self.v100 * 0.00085).max(1e-6);
        
        // ln(mu1) = A + B/t1
        // ln(mu2) = A + B/t2
        // B = ln(mu1/mu2) / (1/t1 - 1/t2)
        self.viscosity_b = (mu1 / mu2).ln() / (1.0/t1 - 1.0/t2);
        self.viscosity_a = mu2.ln() - self.viscosity_b / t2;
    }
}

/// Live state of the oil reservoir.
#[derive(Clone, Debug)]
pub struct OilState {
    pub mass: f32,
    pub temperature: f32,
    pub pressure: f32,
    pub viscosity: f32,
}

impl OilState {
    /// Cold, full-fill, zero pressure.
    pub fn fresh(cfg: &OilConfig) -> Self {
        let temperature = T_ATM;
        Self {
            mass: cfg.capacity,
            temperature,
            pressure: 0.0,
            viscosity: viscosity_for(temperature, cfg.viscosity_a, cfg.viscosity_b, cfg.viscosity_multiplier),
        }
    }

    /// Sump full enough for the pickup to draw.
    #[inline]
    pub fn has_pickup(&self, cfg: &OilConfig) -> bool {
        self.mass > cfg.min_pickup_mass
    }

    /// 0..=1 lubrication regime.  0 = dry boundary, 1 = full hydrodynamic film.
    ///
    /// As long as there's oil in the sump, a residual boundary film clings to
    /// the surfaces — so cold cranking isn't instantly catastrophic.  Active
    /// pump pressure interpolates from that floor up to fully hydrodynamic.
    pub fn lubrication_factor(&self, cfg: &OilConfig) -> f32 {
        if !self.has_pickup(cfg) {
            return 0.0;
        }
        // At extreme temperatures (e.g., > 155°C / 428 K), oil film strength begins to collapse.
        // By 180°C (453 K), it provides almost no protection regardless of pressure.
        let thermal_breakdown = (1.0 - (self.temperature - 428.0) / 25.0).clamp(0.0, 1.0);

        let residual = 0.45;
        let active = (self.pressure / cfg.hydrodynamic_pressure).clamp(0.0, 1.0);
        let base_lube = (residual + (1.0 - residual) * active).clamp(0.0, 1.0);
        
        base_lube * thermal_breakdown
    }

    /// Step the oil one substep.
    ///
    /// `omega`             — current crank speed (rad/s)
    /// `friction_heat_w`   — W of mechanical heat dumped into the oil this step
    /// `cylinder_heat_w`   — W of combustion-side heat the oil absorbs
    /// `dt`                — substep length (s)
    pub fn step(
        &mut self,
        cfg: &OilConfig,
        omega: f32,
        friction_heat_w: f32,
        cylinder_heat_w: f32,
        dt: f32,
    ) {
        // ── Viscosity from current temperature ─────────────────────────────
        self.viscosity = viscosity_for(self.temperature, cfg.viscosity_a, cfg.viscosity_b, cfg.viscosity_multiplier);

        // ── Pump pressure ──────────────────────────────────────────────────
        // Flow rate ∝ rpm.  Pressure ≈ flow * viscosity * lumped resistance.
        // Tuning: ~200 kPa at warm idle (~700 rpm), pinning at relief above ~1500 rpm.
        if self.has_pickup(cfg) {
            const PUMP_RESISTANCE: f32 = 1.5e11; // Pa·s/m³
            let revs_per_s = omega / TAU;
            let flow = (cfg.pump_displacement * revs_per_s).max(0.0);
            let raw_pressure = flow * self.viscosity * PUMP_RESISTANCE;
            let target = raw_pressure.min(cfg.relief_pressure);
            let alpha = (12.0 * dt).min(1.0);
            self.pressure += (target - self.pressure) * alpha;
        } else {
            // Pickup uncovered — pressure collapses immediately.
            self.pressure *= (1.0 - 20.0 * dt).max(0.0);
        }

        const C_OIL: f32 = 2000.0;
        let mass_eff = self.mass.max(0.05);
        let q_in = friction_heat_w + cylinder_heat_w;

        // Oil Cooling System: 
        // 1. Pan dissipation (always active)
        // 2. Oil Cooler (regulated by thermostat)
        let q_pan = cfg.pan_dissipation * (self.temperature - T_ATM);
        
        // Thermostat opens at ~80°C (353 K)
        let therm_open = ((self.temperature - 353.0) / 10.0).clamp(0.0, 1.0);
        let mut cooler_eff = cfg.cooler_dissipation * therm_open;
        if cfg.fan_active {
            cooler_eff *= 3.0; // Cooling fan adds significant airflow
        }
        let q_cooler = cooler_eff * (self.temperature - T_ATM);

        let q_out = q_pan + q_cooler;
        let dT = (q_in - q_out) * dt / (mass_eff * C_OIL);
        self.temperature = (self.temperature + dT).clamp(T_ATM - 5.0, 600.0);

        // ── Extreme heat burn-off ──────────────────────────────────────────
        if self.temperature > 430.0 {
            // Above ~157°C, oil starts evaporating/burning rapidly.
            let burn_rate = (self.temperature - 430.0) * 0.005; // kg/s
            self.consume(burn_rate * dt);
        }
    }

    /// Manually empty the sump (for testing seizure).
    pub fn drain(&mut self) {
        self.mass = 0.0;
        self.pressure = 0.0;
    }

    /// Refill the sump to full and reset temperature.
    pub fn refill(&mut self, cfg: &OilConfig) {
        self.mass = cfg.capacity;
        self.temperature = T_ATM;
        self.pressure = 0.0;
        self.viscosity = viscosity_for(self.temperature, cfg.viscosity_a, cfg.viscosity_b, cfg.viscosity_multiplier);
    }

    /// Burn off some oil mass (e.g. blow-by past worn rings).
    pub fn consume(&mut self, kg: f32) {
        self.mass = (self.mass - kg.max(0.0)).max(0.0);
    }
}

/// Andrade-style viscosity curve: mu = exp(A + B/T)
#[inline]
pub fn viscosity_for(temperature_k: f32, a: f32, b: f32, multiplier: f32) -> f32 {
    let t = temperature_k.max(220.0);
    let base = (a + b / t).exp();
    (base * multiplier).clamp(0.001, 20.0)
}
